import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });
const nunitoFont = Nunito({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Softwareinstore',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={nunitoFont.className}>
            <body className="antialiased">{children}</body>
        </html>
    );
}
